    /{nino}:
      uriParameters:
        nino: types.Nino
      /{taxYear}:
        uriParameters:
          taxYear:  types.TaxYear
        get:
          displayName: List all Benefits GET
          description: Details for Pension Charge submisson
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  type: !include ../zArchive/benefits_sch_GET-TP.json
                  examples:
                    example-1:
                      description: Full data
                      value: !include examples/benefits_full_GET.json
                    example-2:
                      description: Min data
                      value: !include examples/benefits_min_GET.json
        /{benefitId}:
          uriParameters:
            benefitId:  types.BenefitId
          put:
            displayName: Ignore State Benefit PUT
            description: Toggle ignore flag for a State Benefit
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
            body:
              application/json:
                type: !include schemas/benefits_sch_ignore_PUT.json
                examples:
                  example-1:
                    description: Ignore
                    value: !include examples/benefits_ignore_PUT.json
                  example-2:
                    description: Un-ignore
                    value: !include examples/benefits_unignore_PUT.json

            responses:
              200:
        /custom:
          post:
            displayName: Custom Benefit POST
            description: Create customer declared Benefit
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
            body:
              application/json:
                type: !include schemas/benefits_sch_custom_POST.json
                examples:
                  example-1:
                    description: Full data
                    value: !include examples/benefits_full_POST.json
                  example-2:
                    description: Min data
                    value: !include examples/benefits_min_POST.json
            responses:
              201:
                body:
                  application/json:
                    example: !include examples/benefits_custom_POST_resp.json
              400:
              401:
              422:
          /{benefitId}:
            uriParameters:
              benefitId:  types.BenefitId
            put:
              displayName: Custom Benefit PUT
              description: Amend a customer created Benefit
              is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
              body:
                application/json:
                  type: !include schemas/benefits_sch_custom_PUT.json
                  examples:
                    example-1:
                      description: Full request
                      value: !include examples/benefits_full_PUT.json
                    example-2:
                      description: Minimum request
                      value: !include examples/benefits_min_PUT.json
              responses:
                200:
            delete:
              displayName: Custom Benefit DELETE
              description: Delete customer created Benefit
              is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
              responses:
                204: