#%RAML 1.0
title: State Pension & Benefits
baseUri: https://api.service.hmrc.gov.uk/income-received
version: 2020-07-08 16:49
documentation:
  - title: State Pension & Benefits
    content: !include docs/benefits.md
uses:
  errors: ../generic/traits/errors.raml
  genericQueryParameters: ../generic/traits/queryParameters.raml
  wipErrors: traits/errors.raml
  genericHeaders: ../generic/traits/headers.raml
  baseTypes: ../generic/types/common/base-types.raml
/state-benefits:
  !include benefits.raml