#%RAML 1.0
title: Business
baseUri: https://api.service.hmrc.gov.uk/individuals/
version: 2020-07-02 15:18
documentation:
  - title: Property - Periodic Submission
    content: !include docs/property-periodic.md
  - title: Property - Annual Submission
    content: !include docs/property-annual.md
  - title: Business Details
    content: !include docs/details.md
uses:
  errors: ../generic/traits/errors.raml
  genericQueryParameters: ../generic/traits/queryParameters.raml
  wipErrors: traits/errors.raml
  genericHeaders: ../generic/traits/headers.raml
  baseTypes: ../generic/types/common/base-types.raml
/business:
  /property:
    !include property.raml
  /details:
    !include details.raml