#%RAML 1.0
title: Disposals Income
baseUri: https://api.service.hmrc.gov.uk
version: Draft 2021-04-20
documentation:
  - title: Residential Property Disposals
    content: !include docs/residential.md
  - title: Other Disposals & Gains
    content: !include docs/other.md
uses:
  errors: ../generic/traits/errors.raml
  genericQueryParameters: ../generic/traits/queryParameters.raml
  #wipErrors: traits/errors.raml
  genericHeaders: ../generic/traits/headers.raml
  baseTypes: ../generic/types/common/base-types.raml
/income-received/disposals:
  /residential-property:
    /{nino}:
      uriParameters:
        nino: baseTypes.Nino
      /{taxYear}:
        uriParameters:
          taxYear: baseTypes.TaxYear
        get:
          displayName: Residential Property Disposals GET
          description: Retrieve Residential Property Disposals (#1725)
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          queryParameters:
            view:
              displayName: Specify the type of view that you want to see, either HMRC HELD, CUSTOMER or LATEST which combines the HMRC and CUSTOMER views; Implicit default is LATEST
              description: Specify the type of view that you want to see, either HMRC HELD, CUSTOMER or LATEST which combines the HMRC and CUSTOMER views; Implicit default is LATEST
              example: LATEST
              required: false
          responses:
            200:
              body:
                application/json:
                  type: !include schemas/cgt_sch.json
                  examples:
                    example-1:
                      description: LATEST view
                      value: !include examples/cgt_get_latest_example.json
                    example-2:
                      description: HMRC view
                      value: !include examples/cgt_get_hmrc_example.json
                    example-3:
                      description: CUSTOMER view
                      value: !include examples/cgt_get_customer_example.json

        put:
          displayName: Residential Property Disposal PUT
          description: Create/update Residential Property Disposals (#1724)
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              type: !include schemas/cgt_put_residential_sch.json
              example: !include examples/cgt_put_nonppd_example.json
        delete:
          displayName: Residential Property Disposals DELETE
          description: Delete Residential Property Disposals (#1726)
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
        /ppd:
          put:
            displayName: Residential Property Disposal Overrides PUT
            description: Create/update Residential Property Disposal (PPD) Overrides (#1738)
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
            responses:
              200:
            body:
              application/json:
                type: !include schemas/cgt_sch.json
                example: !include examples/cgt_put_ppd_override_example.json
          delete:
            displayName: Residential Property Disposals DELETE
            description: Delete Residential Property Disposal (PPD) Overrides (#1740)
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
            responses:
              204:
        /non-ppd:
  /other-gains:
    /{nino}:
      uriParameters:
        nino: baseTypes.Nino
      /{taxYear}:
        uriParameters:
          taxYear: baseTypes.TaxYear
        put:
          displayName: Other Disposals & Gains PUT
          description: Create/update Other Disposals & Gains (#1739)
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              type: !include schemas/cgt_sch.json
              example: !include examples/cgt_put_other_example.json
        get:
          displayName: Other Disposals & Gains  GET
          description: Retrieve Other Disposals & Gains (#1737)
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  type: !include schemas/cgt_sch.json
                  example: !include examples/cgt_get_other_example.json
        delete:
          displayName: Other Disposals & Gains DELETE
          description: Delete Other Disposals & Gains (#1741)
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
