    /{nino}:
      uriParameters:
        nino: baseTypes.Nino
      /{taxYear}:
        uriParameters:
          taxYear: baseTypes.TaxYear
        get:
          displayName: Other GET
          description: List of other expenses
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/other.json
        put:
          displayName: Other PUT
          description: Create/update other expenses submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              example: !include examples/other.json
        delete:
          displayName: Other DELETE
          description: Delete other expenses submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204: