#%RAML 1.0 Library
uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
traits:
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: No submission could be found for the supplied NINO and tax year.
              value:
                code: MATCHING_RESOURCE_NOT_FOUND
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client and/or agent is not authorised. This is normally because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf.'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
  internalServerError:
      responses:
        500:
          body:
            application/json:
              type: types.errorResponse
              examples:
                clientOrAgentNotAuthorised:
                  description: 'Internal server error'
                  value:
                    code: INTERNAL_SERVER_ERROR

  # FORMAT ERRORS
  formatPartyIdentifier:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatPartyIdentifier:
                description: The format of the supplied party identifier is not valid
                value:
                  code: FORMAT_PARTY_IDENTIFIER
  formatBusinessIdentifier:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                formatBusinessIdentifier:
                  description: The format of the supplied business identifier is not valid
                  value:
                    code: FORMAT_BUSINESS_IDENTIFIER
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTaxYear:
                description: The format of the supplied tax year is not valid
                value:
                  code: FORMAT_TAX_YEAR
  formatStartDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatStartDate:
                description: The format of the supplied start date is not valid
                value:
                  code: FORMAT_START_DATE
  formatEndDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatEndDate:
                description: The format of the supplied end date is not valid
                value:
                  code: FORMAT_END_DATE
  formatType:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                formatType:
                  description: The format of the supplied type field is not valid
                  value:
                    code: FORMAT_TYPE
  formatStatus:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                formatStatus:
                  description: The format of the supplied status field is not valid
                  value:
                    code: FORMAT_STATUS
  formatNino:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                formatStatus:
                  description: The format of the supplied Nino field is not valid
                  value:
                    code: FORMAT_NINO
  #RANGE ERRORS
  rangeEndDateBeforeStartDate:
          responses:
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    rangeEndDateBeforeStartDate:
                      description: The end date is before the start date
                      value:
                        code: RANGE_END_DATE_BEFORE_START_DATE
  #RULE ERRORS
  ruleTaxYearNotSupported:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTaxYearNotSupported:
                description: The specified tax year is not supported, that is, the tax year specified is before the minimum tax year value
                value:
                  code: RULE_TAX_YEAR_NOT_SUPPORTED
  ruleTaxYearRangeExceeded:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTaxYearRangeExceeded:
                description: Tax year range exceeded. A tax year range of one year is required
                value:
                  code: RULE_TAX_YEAR_RANGE_EXCEEDED
  ruleIncorrectOrEmptyBodySubmitted:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleIncorrectOrEmptyBodySubmitted:
                description: An empty or non-matching body was submitted, this could be caused by a missing mandatory field
                value:
                  code: RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED
  #MISSING ERRORS
  missingStartDate:
          responses:
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    missingStartDate:
                      description: The start date parameter is missing
                      value:
                        code: MISSING_START_DATE
  missingEndDate:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  missingEndDate:
                    description: The end date parameter is missing
                    value:
                      code: MISSING_END_DATE
