#%RAML 1.0
title: DRAFT
baseUri: https://api.service.hmrc.gov.uk
version: 2020-05-04 12:27
documentation:
  - title: CIS
    content: |
     | Deduction Type                    | Source | Boxes |
     |:--------------------------------|:-------|:-----------|
     | CIS Deductions                       |   | |
#  - title: CIS Resource Model
#    content: |
#      | Deduction Type | Endpoints | Methods   |
#      |-----------|-----------|-----------|
#      | CIS | /deductions/cis/{nino}/current-position | [GET] |
#      |  | /deductions/cis/{nino}/amendments | [GET] [POST] |
#      |  | /deductions/cis/{nino}/amendments/{submissionId} | [[PUT] [DELETE] |
  - title: Student Loans
    content: |
     | Deduction Type                    | Source | Boxes |
     |:--------------------------------|:-------|:-----------|
     | Student Loans                     | SA100  |  |
#  - title: Student Loans Resource Model
#    content: |
#      | Deduction Type | Endpoints | Methods   |
#      |-----------|-----------|-----------|
#      | Student Loans | /deductions/student-loans/{nino}/{taxYear} | [GET] [PUT] [DELETE] |
  - title: Other
    content: |
     | Other Type                    | Source | Boxes |
     |:--------------------------------|:-------|:-----------|
     | SeaFarers                       | SA101  | ASE box 11|
#  - title: Seafarers Resource Model
#    content: |
#      | Deduction Type | Endpoints | Methods   |
#      |-----------|-----------|-----------|
#      | Others | /deductions/other/{nino}/{taxYear} | [GET] [PUT] [DELETE] |
uses:
  errors: ../generic/traits/errors.raml
  queryParameters: ../generic/traits/queryParameters.raml
  base-types: ../generic/types/common/base-types.raml
/deductions:
  description:
  /cis:
    /{nino}:
      uriParameters:
        nino: base-types.Nino
      /current-position:
        get:
          displayName: List current position of CIS deductions.
          description: List current position of CIS deductions.
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatnino,errors.formatStartDate,errors.formatEndDate,errors.ruleTaxYearRangeExceeded]
          queryParameters:
            fromDate:
              displayName: Start date of the tax year in YYYY-MM-DD
              type: date-only
              description:  Start date of the tax year in YYYY-MM-DD
              example: 2018-04-06
              required: true
            toDate:
              displayName: End date of the tax year in YYYY-MM-DD
              type: date-only
              description: End date of the tax year in YYYY-MM-DD
              example: 2019-04-05
              required: true
            source:
              displayName: Source of CIS Deductions i.e. those supplied by the Contractor, the Customer; Implicit default is All
              description: Source of CIS Deductions i.e. those supplied by the Contractor, the Customer; Implicit default is All
              example: customer
              required: false
          responses:
            200:
              body:
                application/json:
                  example: !include examples/cis_deductions_position_blended.json
      /amendments:
        post:
          displayName: Create CIS deductions amendments for a Contractor & Tax Year
          description: Create CIS deductions amendments for a Contractor & Tax Year
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatnino,errors.formatStartDate,errors.formatEndDate,errors.ruleTaxYearRangeExceeded]
          responses:
            200:
          body:
            application/json:
              example: !include examples/cis_deductions_amendments_post.json
        /{submissionId}:
          uriParameters:
            submissionId: base-types.SubmissionId  #TODO check that regex is correct
          put:
            displayName: Update CIS deductions amendments for a Contractor & Tax Year
            description: Update CIS deductions amendments for a Contractor & Tax Year
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatnino,errors.formatStartDate,errors.formatEndDate,errors.ruleTaxYearRangeExceeded]
            responses:
              200:
            body:
              application/json:
                example: !include examples/cis_deductions_amendments_put.json
          delete:
            displayName: Delete CIS deductions amendments for a Contractor & Tax Year
            description: Delete CIS deductions amendments for a Contractor & Tax Year
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatnino]
            responses:
              204:
  /student-loans:
    /{nino}:
      uriParameters:
        nino: base-types.Nino
      /{taxYear}:
        uriParameters:
          taxYear: base-types.TaxYear
        get:
          displayName: List of Student Loans deductions
          description: List of Student Loans deductions
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/sl_deduction_override.json
        put:
          displayName: Create/update Student Loans submission
          description: Create/update Student Loans submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino]
          responses:
            200:
          body:
            application/json:
              example: !include examples/sl_deduction_override.json
        delete:
          displayName: Delete Student Loans submission
          description: Delete Student Loans submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
  /other:
    /{nino}:
      uriParameters:
        nino: base-types.Nino
      /{taxYear}:
        uriParameters:
          taxYear: base-types.TaxYear
        get:
          displayName: List of other deductions
          description: List of other deductions
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/other_deductions.json
        put:
          displayName: Create/update other deductions submission
          description: Create/update other deductions submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino]
          responses:
            200:
          body:
            application/json:
              example: !include examples/other_deductions.json
        delete:
          displayName: Delete other deductions submission
          description: Delete other deductions submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
