#%RAML 1.0
title: DRAFT Deductions MTD
baseUri: https://api.service.hmrc.gov.uk
version: 0.5
documentation:
  - title: Resource Model
    content: |
      | Deduction Type | Endpoints | Methods   |
      |-----------|-----------|-----------|
      | CIS | /deductions/cis/{taxableEntityId}/current-position | [GET] |
      |  | /deductions/cis/{taxableEntityId}/amendments | [GET] [POST] |
      |  | /deductions/cis/{taxableEntityId}/amendments/{submissionId} | [[PUT] [DELETE] |
      | Student Loans | /deductions/student-loans/{taxableEntityId}/current-position | [GET] |
      |  | /deductions/student-loans/{taxableEntityId}/amendments | [GET] [POST] |
      |  | /deductions/student-loans/{taxableEntityId}/amendments/{submissionId} | [[PUT] [DELETE] |
uses:
  errors: ../generic/traits/errors.raml
  queryParameters: ../generic/traits/queryParameters.raml
  base-types: ../generic/types/common/base-types.raml
/deductions:
  /cis:
    /{taxableEntityId}:
      uriParameters:
        taxableEntityId:
          description: Unique identifier of the taxable entity to which the submission belongs i.e. NINO for an individual
          type: base-types.taxableEntityId
      /current-position:
        get:
          displayName: List current position of CIS deductions.
          description: List current position of CIS deductions.
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formattaxableEntityId,errors.formatStartDate,errors.formatEndDate,errors.ruleTaxYearRangeExceeded]
          queryParameters:
            fromDate:
              displayName: Start date of the tax year in YYYY-MM-DD
              type: date-only
              description:  Start date of the tax year in YYYY-MM-DD
              example: 2018-04-06
              required: true
            toDate:
              displayName: End date of the tax year in YYYY-MM-DD
              type: date-only
              description: End date of the tax year in YYYY-MM-DD
              example: 2019-04-05
              required: true
            source:
              displayName: Source of CIS Deductions i.e. those supplied by the Contractor, the Customer or all (blended)
              description: Source of CIS Deductions i.e. those supplied by the Contractor, the Customer or all (blended)
              example: all
              default: all
              required: true
          responses:
            200:
              body:
                application/json:
                  example: !include examples/cis_deductions_position_blended.json
      /amendments:
        post:
          displayName: Create CIS deductions amendments for a Contractor & Tax Year
          description: Create CIS deductions amendments for a Contractor & Tax Year
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formattaxableEntityId,errors.formatStartDate,errors.formatEndDate,errors.ruleTaxYearRangeExceeded]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/cis_deductions_amendments_response.json
          body:
            application/json:
              example: !include examples/cis_deductions_amendments_post.json
        /{submissionId}:
          uriParameters:
            submissionId:
              description: Id for the  CIS deduction amendments collection
              type: string
              example: S4636A77V5KB8625U
          put:
            displayName: Update CIS deductions amendments for a Contractor & Tax Year
            description: Update CIS deductions amendments for a Contractor & Tax Year
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formattaxableEntityId,errors.formatStartDate,errors.formatEndDate,errors.ruleTaxYearRangeExceeded]
            responses:
              200:
            body:
              application/json:
                example: !include examples/cis_deductions_amendments_put.json
          delete:
            displayName: Delete CIS deductions amendments for a Contractor & Tax Year
            description: Delete CIS deductions amendments for a Contractor & Tax Year
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formattaxableEntityId]
            responses:
              204:
  /student-loans:
    /{taxableEntityId}:
      uriParameters:
        taxableEntityId:
          description: Unique identifier of the taxable entity to which the submission belongs i.e. NINO for an individual
          type: base-types.taxableEntityId
      /current-position:
        get:
          displayName: List current position of Student Loans.
          description: List current position of Student Loans.
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formattaxableEntityId,errors.formatStartDate,errors.formatEndDate,errors.ruleTaxYearRangeExceeded]
          queryParameters:
            fromDate:
              displayName: Start date of the tax year in YYYY-MM-DD
              type: date-only
              description:  Start date of the tax year in YYYY-MM-DD
              example: 2018-04-06
              required: true
            toDate:
              displayName: End date of the tax year in YYYY-MM-DD
              type: date-only
              description: End date of the tax year in YYYY-MM-DD
              example: 2019-04-05
              required: true
            source:
              displayName: Source of Student Loans i.e. those supplied by the Employer, the Customer or all (blended)
              description: Source of Student Loans i.e. those supplied by the Employer, the Customer or all (blended)
              example: all
              default: all
              required: true
          responses:
            200:
              body:
                application/json:
                  example: !include examples/cis_deductions_position_blended.json
      /amendments:
        post:
          displayName: Create Student Loan deductions amendments for an Employment & Tax Year
          description: Create Student Loan deductions amendments for an Employment & Tax Year
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formattaxableEntityId,errors.formatStartDate,errors.formatEndDate,errors.ruleTaxYearRangeExceeded]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/cis_deductions_amendments_response.json
          body:
            application/json:
              example: !include examples/cis_deductions_amendments_post.json
        /{submissionId}:
          uriParameters:
            submissionId:
              description: Id for the  CIS deduction amendments collection
              type: string
              example: S4636A77V5KB8625U
          put:
            displayName: Update Create Student Loan deductions amendments for an Employment & Tax Year
            description: Update Create Student Loan deductions amendments for an Employment & Tax Year
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formattaxableEntityId,errors.formatStartDate,errors.formatEndDate,errors.ruleTaxYearRangeExceeded]
            responses:
              200:
            body:
              application/json:
                example: !include examples/cis_deductions_amendments_put.json
          delete:
            displayName: Delete Student Loan deductions amendments for an Employment & Tax Year
            description: Delete Student Loan deductions amendments for an Employment & Tax Year
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formattaxableEntityId]
            responses:
              204:
