#%RAML 1.0
title: Obligations
baseUri: https://api.service.hmrc.gov.uk
version: 2020-06-18 08:46
documentation:
  - title: Obligations
    content: |
     | Obligation Type                    | Source | Boxes |
     |:--------------------------------|:-------|:-----------|
     | Income Tax                      |   | |
uses:
  genericErrors: ../generic/traits/errors.raml
  genericQueryParameters: ../generic/traits/queryParameters.raml
  obligationQueryParameters: traits/queryParameters.raml
  obligationErrors: traits/errors.raml
  genericHeaders: ../generic/traits/headers.raml
  baseTypes: ../generic/types/common/base-types.raml
/obligations:
  /{nino}:
    uriParameters:
      nino: baseTypes.Nino
    /income-tax:
      get:
        displayName: Obligations GET
        description: List income tax obligations for the party
        is: [genericErrors.internalServerError,
             genericErrors.notFound,
             genericErrors.clientOrAgentNotAuthorised,
             genericErrors.formatnino,
             genericErrors.formatStartDate,
             genericErrors.formatEndDate,
             genericErrors.formatType,
             genericErrors.rangeEndDateBeforeStartDate,
             obligationErrors.ruleDateRangeInvalid,
             obligationErrors.ruleStartDateNotSupported,
             obligationErrors.rangeDateTooLong,
             genericErrors.missingStartDate,
             genericErrors.missingEndDate,
             obligationQueryParameters.obligations-regime,
             genericQueryParameters.startEndDateRange,
             genericHeaders.standardHeaders]
        responses:
          200:
            body:
              application/json:
                example: !include examples/by-regime/income-tax.json