#%RAML 1.0 Library
uses:
  common-base-types: ../common/base-types.raml
types:
  TriggerTaxCalculationResponse:
    type: object
    properties:
      id: common-base-types.CalcId
      _links: common-base-types.Links
