#%RAML 1.0 Library
traits:
  taxYear:
    queryParameters:
      taxYear:
        type: string
        description: The tax year the data applies to, for example, 2017-18. If no tax year is supplied calculations for the current tax year will be returned. The start year and end year must not span two tax years. No gaps are allowed, for example, 2019-21 is not valid. The minimum tax year is 2017-18.
        example: "2017-18"
        required: false
  message-types:
    queryParameters:
      info:
          description: Whether info messages should be included in the response
          type: boolean
          required: false
      warnings:
          description: Whether warning messages should be included in the response
          type: boolean
          required: false
      errors:
          description: Whether error messages should be included in the response
          type: boolean
          required: false
  obligations:
    queryParameters:
      source:
          description: The source context for the obligation e.g. self employment business
          type: string
          enum: ["selfEmployment","ukProperty","foreignProperty"]
          required: false
      sourceId:
          description: The associated source identifier for the obligation
          type: string
          required: false
      type:
          description: The type of obligation
          enum: ["incomeAndExpenses", "selfAssessmentCrystallisation", "vatReturn", "selfAssessmentEndOfPeriodStatement"]
          type: string
          required: true
      status:
          description: The type of obligation
          enum: ["open", "fulfilled"]
          type: string
          required: false
      start:
          description: The start date to filter obligations by
          type: date-only
          required: false
      end:
          description: The end date to filter obligations by
          type: date-only
          required: false
