#%RAML 1.0
title: DRAFT
baseUri: https://api.service.hmrc.gov.uk
version:
documentation:
  - title: Expenses
    content: |
     | Expenses Type                                | Source | Boxes      |
     |:--------------------------------------------|:-------|:-----------|
     | Payments to Trade Unions for Death Benefits | SA101  | AOR Box 8  |
     | Patent Royalties                            | SA101  | ASE Box 15 |
    #  - title: Resource Model
#    content: |
#      | Expense Type | Endpoints | Methods   |
#      |-----------|-----------|-----------|
#      | Other | /expenses/other/{nino}/{taxYear} | [POST] [GET] [PUT] |
#      ---
uses:
  errors: ../generic/traits/errors.raml
  genericQueryParameters: ../generic/traits/queryParameters.raml
  wipErrors: traits/errors.raml
  genericHeaders: ../generic/traits/headers.raml
  baseTypes: ../generic/types/common/base-types.raml
/expenses:
  /other:
    /{nino}:
      uriParameters:
        nino: baseTypes.Nino
      /{taxYear}:
        uriParameters:
          taxYear: baseTypes.TaxYear
        get:
          displayName: List of other expenses
          description: List of other expenses
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/expenses.json.json
        put:
          displayName: Create/update other expenses submission
          description: Create/update other expenses submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              example: !include examples/expenses.json
        delete:
          displayName: Delete other expenses submission
          description: Delete other expenses submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
