#%RAML 1.0
title: DRAFT
baseUri: https://api.service.hmrc.gov.uk
version: 2020-05-19 15:04
documentation:
  - title: Other
    content: !include docs/other.md
uses:
  errors: ../generic/traits/errors.raml
  genericQueryParameters: ../generic/traits/queryParameters.raml
  wipErrors: traits/errors.raml
  genericHeaders: ../generic/traits/headers.raml
  baseTypes: ../generic/types/common/base-types.raml
/expenses:
  /employments:
    !include employments.raml
  /other:
    !include other.raml