#%RAML 1.0
title: DRAFT
baseUri: https://api.service.hmrc.gov.uk
version: 2020-05-12 12:26
documentation:
  - title: Disclosures
    content: |
     | Disclosure Type                    | Source | Boxes                     |
     |:--------------------------------|:-------|:--------------------------|
     | Tax Avoidance                   | SA101  | Tax Avoidance Box 19 - 20 |
#  - title: Resource Model
#    content: |
#      | Dosclosure Type | Endpoints | Methods   |
#      |-----------|-----------|-----------|
#      | Tax Avoidance | /disclosures/{nino}/{taxYear} | [GET] [PUT] [DELETE] |
#      ___
uses:
  errors: ../generic/traits/errors.raml
  genericQueryParameters: ../generic/traits/queryParameters.raml
  wipErrors: traits/errors.raml
  genericHeaders: ../generic/traits/headers.raml
  baseTypes: ../generic/types/common/base-types.raml
/disclosures:
  /{nino}:
    uriParameters:
      nino: baseTypes.Nino
    /{taxYear}:
      uriParameters:
        taxYear: baseTypes.TaxYear
      get:
        displayName: List of Disclosures
        description: List of Disclosures
        is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
        responses:
          200:
            body:
              application/json:
                example: !include examples/disclosures.json
      put:
        displayName: Create/update Disclosures submission
        description: Create/update Disclosures submission
        is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
        responses:
          200:
        body:
          application/json:
            example: !include examples/disclosures.json
      delete:
        displayName: Delete Disclosures submission
        description: Delete Disclosures submission
        is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
        responses:
          204:
