#%RAML 1.0
title: DRAFT Obligations by Regime
baseUri: https://api.service.hmrc.gov.uk
version: 0.1
documentation:
  - title: Obligations
    content: |
     | Obligation Type                    | Source | Boxes |
     |:--------------------------------|:-------|:-----------|
     | Income Tax                      |   | |
#  - title: Resource Model
#    content: |
#      | Endpoints |
#      ------------
#      | /obligations/{taxableEntityId}/income-tax [GET] |
#      ___
uses:
  genericErrors: ../generic/traits/errors.raml
  genericQueryParameters: ../generic/traits/queryParameters.raml
  obligationQueryParameters: traits/queryParameters.raml
  obligationErrors: traits/errors.raml
  genericHeaders: ../generic/traits/headers.raml
/obligations:
  /{taxableEntityId}:
    uriParameters:
      taxableEntityId:
        description: Party identifier, NINO for SA Individuals
        type: string
        pattern: ^([ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-T-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D]?$
        example: TC663795B
    /income-tax:
      get:
        displayName: List income tax obligations for the party
        description: List income tax obligations for the party
        is: [genericErrors.internalServerError,
             genericErrors.notFound,
             genericErrors.clientOrAgentNotAuthorised,
             genericErrors.formattaxableEntityId,
             genericErrors.formatStartDate,
             genericErrors.formatEndDate,
             genericErrors.formatType,
             genericErrors.rangeEndDateBeforeStartDate,
             obligationErrors.ruleDateRangeInvalid,
             obligationErrors.ruleStartDateNotSupported,
             obligationErrors.rangeDateTooLong,
             genericErrors.missingStartDate,
             genericErrors.missingEndDate, |
             obligationQueryParameters.obligations-regime,
             genericQueryParameters.startEndDateRange,
             genericHeaders.standardHeaders]
        responses:
          200:
            body:
              application/json:
                example: !include examples/by-regime/income-tax.jsonq