#%RAML 1.0
title: DRAFT Business Details
baseUri: https://api.service.hmrc.gov.uk
version: 0.1
uses:
  genericErrors: ../generic/traits/errors.raml
/business-details:
  /{partyIdentifier}:
    uriParameters:
      partyIdentifier:
        description: Party identifier, NINO for SA Individuals
        type: string
        pattern: ^([ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-T-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D]?$
        example: TC663795B
    /self-employments:
      get:
        displayName: List self employment businesses
        description: List self employment businesses
        is: [genericErrors.notFound,genericErrors.clientOrAgentNotAuthorised]
        responses:
          200:
            body:
              application/json:
                example: !include examples/self-employment-business.json
