#%RAML 1.0
title: DRAFT Business Details
baseUri: https://api.service.hmrc.gov.uk
version: 2020-05-04 15:29
documentation:
- title: Assumptions
  content: ' <ol>
                <li>Object schemas from backend [DES] API for self-employment businesses and properties are the same</li>
             </ol>'
- title: Design Rationale
  content: 'The data schemas for business and property are thought to be the same (or very similar), so it made sense to combine everything in one GET "list" and one GET "details".  If we need to add further types of business details in future we can extend with finer-grained end-points as non-breaking changes.'
- title: Business Details
  content: |
   | Details Type                    | Source | Boxes                     |
   |:--------------------------------|:-------|:--------------------------|
   | Business Details                   |   |  |
#- title: Resource Model
#  content: |
#    | Type | Endpoints | Methods   |
#    |-----------|-----------|-----------|
#    | Business | /business-details/{partyIdentifier} | [GET] |
#    | Business | /business-details/{partyIdentifier}/{id} |[PUT] [DELETE] |
#    ___
uses:
  genericErrors: ../generic/traits/errors.raml
/business-details:
  /{partyIdentifier}:
    uriParameters:
      partyIdentifier:
        description: Party identifier, NINO for SA Individuals
        type: string
        pattern: ^([ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-T-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D]?$
        example: TC663795B
    get:
      displayName: List all businesses
      description: List all businesses
      is: [genericErrors.notFound,genericErrors.clientOrAgentNotAuthorised]
      queryParameters:
        typeOfBusiness:
          displayName: self-employment | uk-property | foreign-property
          description: self-employment | uk-property | foreign-property
          example: self-employment
          required: false
      responses:
        200:
          body:
            application/json:
              example: !include ../business/examples/all-business-list.json
    /{businessId}:
      uriParameters:
        id:
          description: Business Id
          type: string
          example: XGIS00000001319
      get:
        displayName: Retrieve businesses detail
        description: Retrieve businesses detail
        is: [genericErrors.notFound,genericErrors.clientOrAgentNotAuthorised,genericErrors.formatNino,genericErrors.ruleTaxYearNotSupported,genericErrors.ruleTaxYearRangeExceeded,genericErrors.formatTaxYear]
        responses:
          200:
            body:
              application/json:
                example: !include examples/business-details.json
