#%RAML 1.0
title: DRAFT
baseUri: https://api.service.hmrc.gov.uk
version: 2020-05-19 15:04
documentation:
  - title: Investment
    content: |
     | Investment Type                 | Source | Boxes        |
     |:-----------------------------|:-------|:-------------|
     | VCT Subscriptions            | SA101  | AOR Box 1    |
     | EIS Subscriptions            | SA101  | AOR Box 2    |
     | Community Investment         | SA101  | AOR Box 3    |
     | Seed Enterprise Investment   | SA101  | AOR Box 10   |
     | Social Enterprise Investment | SA101  | AOR Box 11   |
#  - title: Resource Model
#    content: |
#      | Relief Type | Endpoints | Methods   |
#      |-----------|-----------|-----------|
#      | Investment | /reliefs/investment/{nino}/{taxYear} | [GET] [PUT] [DELETE] |
#      ___
  - title: Other
    content: |
     | Other Type                                                | Source | Boxes                   |
     |:------------------------------------------------------------|:-------|:------------------------|
     | Non Deductable Loan Interest                                | SA101  | AOR Box 12              |
     | Payroll Giving                                              | SA101  | Other Information box 6 |
     | Qualifying Distribution Redemption Of Shares and Securities | SA101  | AOR box 9               |
     | Post Cessation Trade Relief and Certain Other Losses        | SA101  | AOR box 6               |
     | Maintenance Payments                                        | SA101  | AOR box 7               |
     | Annual Payments Made                                        | SA101  |                         |
     | Qualifying Loan Interest Payments                           | SA101  |                         |
#  - title: Resource Model
#    content: |
#      | Relief Type | Endpoints | Methods   |
#      |-----------|-----------|-----------|
#      | Other | /reliefs/other/{nino}/{taxYear} | [GET] [PUT] [DELETE] |
#      ___
  - title: Foreign
    content: |
     | Foreign Type                    | Source | Boxes  |
     |:--------------------------------|:-------|:-------|
     | Foreign Tax Credit Relief       | SA106  | Box 2  |
#  - title: Resource Model
#    content: |
#      | Relief Type | Endpoints | Methods   |
#      |-----------|-----------|-----------|
#      | Foreign | /reliefs/foreign/{nino}/{taxYear} | [GET] [PUT] [DELETE] |
#      ___
uses:
  errors: ../generic/traits/errors.raml
  genericQueryParameters: ../generic/traits/queryParameters.raml
  wipErrors: traits/errors.raml
  genericHeaders: ../generic/traits/headers.raml
  baseTypes: ../generic/types/common/base-types.raml
/reliefs:
  /investment:
    /{nino}:
      uriParameters:
        nino: baseTypes.Nino
      /{taxYear}:
        uriParameters:
          taxYear: baseTypes.TaxYear
        get:
          displayName: List of Investment Reliefs
          description: List of Investment Reliefs
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/investment.json
        put:
          displayName: Create/update Investment Reliefs submission
          description: Create/update Investment Reliefs submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              example: !include examples/investment.json
        delete:
          displayName: Delete Investment Reliefs submission
          description: Delete Investment Reliefs submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
  /other:
    /{nino}:
      uriParameters:
        nino: baseTypes.Nino
      /{taxYear}:
        uriParameters:
          taxYear: baseTypes.TaxYear
        get:
          displayName: List of Other Reliefs
          description: List of Other  Reliefs
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/other.json
        put:
          displayName: Create/update Other Reliefs submission
          description: Create/update Other Reliefs submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              example: !include examples/other.json
        delete:
          displayName: Delete Other Reliefs submission
          description: Delete Other Reliefs submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
  /foreign:
    /{nino}:
      uriParameters:
        nino: baseTypes.Nino
      /{taxYear}:
        uriParameters:
          taxYear: baseTypes.TaxYear
        get:
          displayName: List of foreign Reliefs
          description: List of foreign  Reliefs
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/reliefs-foreign.json
        put:
          displayName: Create/update foreign Reliefs submission
          description: Create/update foreign Reliefs submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              example: !include examples/reliefs-foreign.json
        delete:
          displayName: Delete foreign Reliefs submission
          description: Delete foreign Reliefs submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
  /pensions:
