#%RAML 1.0
title: DRAFT
baseUri: https://api.service.hmrc.gov.uk
version: 0.1
documentation:
  - title: Resource Model
    content: |
      | Income Type | Endpoints | Methods   |
      |-----------|-----------|-----------|
      | Property | /income/property/{taxableEntityId}/{incomeSourceId} | [POST] [GET] |
      |          | /income/property/{taxableEntityId}/{incomeSourceId}/{submissionId} | [PUT] [GET] |
      | Savings | /income/savings/{taxableEntityId}/{taxYear} | [GET] [PUT] [DELETE] |
      | Insurance Policies | /income/insurance-policies/{taxableEntityId}/{taxYear} | [GET] [PUT] [DELETE] |
      | Other Employment | /income/employment/other/{taxableEntityId}/{taxYear} | [GET] [PUT] [DELETE] |
      | Foreign | /income/foreign/{taxableEntityId}/{taxYear} | [GET] [PUT] [DELETE] |
      | Dividends | /income/dividends/{taxableEntityId}/{taxYear} | [GET] [PUT] [DELETE] |
      | Pensions | /income/pensions/{taxableEntityId}/{taxYear} | [GET] [PUT] [DELETE] |
      | Other | /income/other/{taxableEntityId}/{taxYear} | [GET] [PUT] [DELETE] |
uses:
  errors: ../generic/traits/errors.raml
  genericQueryParameters: ../generic/traits/queryParameters.raml
  wipErrors: traits/errors.raml
  genericHeaders: ../generic/traits/headers.raml
  baseTypes: ../generic/types/common/base-types.raml
/income:
  /property:
    /{taxableEntityId}:
      uriParameters:
        taxableEntityId: baseTypes.TaxableEntityId
      /{incomeSourceId}:
        uriParameters:
          incomeSourceId: baseTypes.IncomeSourceId
        post:
          displayName: Create property income submission
          description: Create property income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino]
          responses:
            200:
          body:
            application/json:
              example: !include examples/property-post.json
        get:
          displayName: List of property income
          description: List of property income
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/property-list.json
        /{submissionId}:
          uriParameters:
            submissionId: baseTypes.SubmissionId
          put:
            displayName: Create/update property income submission
            description: Create/update property income submission
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino]
            responses:
              200:
            body:
              application/json:
                example: !include examples/property.json
          get:
            displayName: Retrieve property income by submission
            description: Retrieve property income by submission
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino]
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/property-withid.json
  /savings:
    /{taxableEntityId}:
      uriParameters:
        taxableEntityId: baseTypes.TaxableEntityId
      /{taxYear}:
        uriParameters:
          taxYear: baseTypes.TaxYear
        get:
          displayName: List of savings income
          description: List of savings income
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/savings.json
        put:
          displayName: Create/update savings income submission
          description: Create/update savings income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              example: !include examples/savings.json
        delete:
          displayName: Delete savings income submission
          description: Delete savings income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
  /insurance-policies:
    /{taxableEntityId}:
      uriParameters:
          taxableEntityId: baseTypes.TaxableEntityId
      /{taxYear}:
        uriParameters:
          taxYear: baseTypes.TaxYear
        get:
          displayName: List of Insurance Policies income
          description: List of Insurance Policies income
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/insurance.json
        put:
          displayName: Create/update Insurance Policies income submission
          description: Create/update Insurance Policies income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino]
          responses:
            200:
          body:
            application/json:
              example: !include examples/insurance.json
        delete:
          displayName: Delete Insurance Policies income submission
          description: Delete Insurance Policies income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
  /employment:
    /other:
      /{taxableEntityId}:
        uriParameters:
            taxableEntityId: baseTypes.TaxableEntityId
        /{taxYear}:
          uriParameters:
            taxYear: baseTypes.TaxYear
          get:
            displayName: List of Other Employment income
            description: List of Other Employment income
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/emp-other.json
          put:
            displayName: Create/update Other Employment income submission
            description: Create/update Other Employment income submission
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino]
            responses:
              200:
            body:
              application/json:
                example: !include examples/emp-other.json
          delete:
            displayName: Delete Other Employment income submission
            description: Delete Other Employment income submission
            is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
            responses:
              204:
  /foreign:
    /{taxableEntityId}:
      uriParameters:
          taxableEntityId: baseTypes.TaxableEntityId
      /{taxYear}:
        uriParameters:
          taxYear: baseTypes.TaxYear
        get:
          displayName: List of Foreign income
          description: List of Foreign income
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/foreign.json
        put:
          displayName: Create/update Foreign income submission
          description: Create/update Foreign income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino]
          responses:
            200:
          body:
            application/json:
              example: !include examples/foreign.json
        delete:
          displayName: Delete Foreign income submission
          description: Delete Foreign income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
  /dividends:
    /{taxableEntityId}:
      uriParameters:
        taxableEntityId: baseTypes.TaxableEntityId
      /{taxYear}:
        uriParameters:
          taxYear: baseTypes.TaxYear
        get:
          displayName: List of dividends income
          description: List of dividends income
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/dividends.json
        put:
          displayName: Create/update dividends income submission
          description: Create/update dividends income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              example: !include examples/dividends.json
        delete:
          displayName: Delete dividends income submission
          description: Delete dividends income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
  /pensions:
    /{taxableEntityId}:
      uriParameters:
        taxableEntityId: baseTypes.TaxableEntityId
      /{taxYear}:
        uriParameters:
          taxYear: baseTypes.TaxYear
        get:
          displayName: List of pensions income
          description: List of pensions income
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/pensions.json
        put:
          displayName: Create/update pensions income submission
          description: Create/update pensions income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              example: !include examples/pensions.json
        delete:
          displayName: Delete pensions income submission
          description: Delete pensions income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
  /other:
    /{taxableEntityId}:
      uriParameters:
        taxableEntityId: baseTypes.TaxableEntityId
      /{taxYear}:
        uriParameters:
          taxYear: baseTypes.TaxYear
        get:
          displayName: List of other income
          description: List of other income
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/other.json
        put:
          displayName: Create/update other income submission
          description: Create/update other income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              example: !include examples/other.json
        delete:
          displayName: Delete other income submission
          description: Delete other income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
#  /$NAME$:
#    /{taxableEntityId}:
#      uriParameters:
#        taxableEntityId: baseTypes.TaxableEntityId
#      /{taxYear}:
#        uriParameters:
#          taxYear: baseTypes.TaxYear
#        get:
#          displayName: List of $NAME$ income
#          description: List of $NAME$ income
#          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
#          responses:
#            200:
#              body:
#                application/json:
#                  example: !include examples/$NAME$.json
#        put:
#          displayName: Create/update $NAME$ income submission
#          description: Create/update $NAME$ income submission
#          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
#          responses:
#            200:
#          body:
#            application/json:
#              example: !include examples/$NAME$.json
#        delete:
#          displayName: Delete $NAME$ income submission
#          description: Delete $NAME$ income submission
#          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
#          responses:
#            204:
