    /{nino}:
      uriParameters:
        nino: types.Nino
      /{taxYear}:
        uriParameters:
          taxYear:  types.TaxYear
        get:
          displayName: Dividends GET (list)
          description: List of dividends income
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/dividends.json
        put:
          displayName: Dividends PUT
          description: Create/update dividends income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              example: !include examples/dividends.json
        delete:
          displayName: Dividends DELETE
          description: Delete dividends income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
          responses:
            204: