    /{nino}:
      uriParameters:
        nino: types.Nino
      /{taxYear}:
        uriParameters:
          taxYear:  types.TaxYear
        get:
          displayName: Foreign GET (list)
          description: List of Foreign income
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/foreign.json
        put:
          displayName: Foreign PUT
          description: Create/update Foreign income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate]
          responses:
            200:
          body:
            application/json:
              example: !include examples/foreign.json
        delete:
          displayName: Foreign DELETE
          description: Delete Foreign income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
          responses:
            204: