    /{nino}:
      uriParameters:
        nino: types.Nino
      /{taxYear}:
        uriParameters:
          taxYear:  types.TaxYear
        get:
          displayName: List of pensions income
          description: List of pensions income
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/pensions.json
        put:
          displayName: Create/update pensions income submission
          description: Create/update pensions income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              example: !include examples/pensions.json
        delete:
          displayName: Delete pensions income submission
          description: Delete pensions income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
          responses:
            204: