#%RAML 1.0 Library
uses:
  base-objects: base-types/types.raml
types:
  AllowancesDeductionsReliefs:
    type: object
    properties:
      detail: base-objects.Detail
      summary: base-objects.Summary
