    /{nino}:
      uriParameters:
        nino: types.Nino
      /{taxYear}:
        uriParameters:
          taxYear:  types.TaxYear
        get:
          displayName: Other GET (list)
          description: List of other income
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/other.json
        put:
          displayName: Other PUT
          description: Create/update other income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              example: !include examples/other.json
        delete:
          displayName: Other DELETE
          description: Delete other income submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatToDate,errors.formatTaxYear]
          responses:
            204: