#%RAML 1.0
title: DRAFT SA101/106
baseUri: https://api.service.hmrc.gov.uk
version: 0.1
documentation:
  - title: About
    content:  Mega-monolith API to try and assemble the various structures for SA101/106.  Will break up into suitable discrete APIs.
  - title: Resource Model
    content: |
      | Endpoints | Methods   |
      |-----------|-----------|
      | /income/insurance-policies/{taxableEntityId}/ | [POST] [UPDATE] [DELETE] [GET]|
      | /income/securities/{taxableEntityId}/ |  [POST] [UPDATE] [DELETE] [GET]|
      | /income/interest/{taxableEntityId}/ |  [POST] [UPDATE] [DELETE] [GET]|
      | /income/business/{taxableEntityId}/ | [POST] [UPDATE] [DELETE] [GET]|
      | /income/foreign/{taxableEntityId}/ | [POST] [UPDATE] [DELETE] [GET]|
      | /deductions/{deductionType}/{taxableEntityId}/ |  [POST] [UPDATE] [DELETE] [GET]|
      | /deductions/cis/{taxableEntityId}/ |  [POST] [UPDATE] [DELETE] [GET]|
      | /deductions/student-loans/{taxableEntityId}/ |  [POST] [UPDATE] [DELETE] [GET]|
      | /deductions/other/{taxableEntityId}/ |  [POST] [UPDATE] [DELETE] [GET]|




      | /income/dividends/{taxableEntityId}/ |  [POST] [UPDATE] [DELETE] [GET]|
      | /income/loans/{taxableEntityId}/ | [POST] [UPDATE] [DELETE] [GET]|
      | /income/other/{taxableEntityId}/ | [POST] [UPDATE] [DELETE] [GET]|
      | /income/interest/{taxableEntityId}/ | [POST] [UPDATE] [DELETE] [GET]|
      | /income/employment/{taxableEntityId}/ | [POST] [UPDATE] [DELETE] [GET] |
      | /income/securities/{taxableEntityId}/ |  [POST] [UPDATE] [DELETE] [GET]|
      | /income/property/{taxableEntityId}/ |  [POST] [UPDATE] [DELETE] [GET]|
      | /reliefs//{taxableEntityId}/ | [POST] [UPDATE] [DELETE] [GET]|
      | /allowances/t/{taxableEntityId}/ | [POST] [UPDATE] [DELETE] [GET]|
uses:
  genericErrors: ../generic/traits/errors.raml
  genericQueryParameters: ../generic/traits/queryParameters.raml
  wipQueryParameters: traits/queryParameters.raml
  wipErrors: traits/errors.raml
  genericHeaders: ../generic/traits/headers.raml
/income:
  /employment:
    /{taxableEntityId}:
      uriParameters:
        taxableEntityId:
          description: Unique entity identifier, NINO for SA Individuals
          type: string
          pattern: ^([ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-T-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D]?$
          example: TC663795B
      post:
        displayName: employment
        description: employment
        is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatStartDate,errors.formatEndDate,errors.ruleTaxYearRangeExceeded]
        responses:
          200:
            body:
              application/json:
                #example: !include examples/cis_deductions_amendments_response.json
        body:
          application/json:
            example: !include examples/cis_deductions_amendments_post.json
  /securities:
    /{taxableEntityId}:
      uriParameters:
        taxableEntityId:
          description: Unique entity identifier, NINO for SA Individuals
          type: string
          pattern: ^([ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-T-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D]?$
          example: TC663795B
  /insurance-policies:
    /{taxableEntityId}:
      uriParameters:
        taxableEntityId:
          description: Unique entity identifier, NINO for SA Individuals
          type: string
          pattern: ^([ACEHJLMOPRSWXY][A-CEGHJ-NPR-TW-Z]|B[A-CEHJ-NPR-TW-Z]|G[ACEGHJ-NPR-T-Z]|[KT][A-CEGHJ-MPR-TW-Z]|N[A-CEGHJL-NPR-SW-Z]|Z[A-CEGHJ-NPR-TW-Y])[0-9]{6}[A-D]?$
          example: TC663795B
  #    /income-tax:
  #      get:
  #        displayName: List income tax obligations for the party
  #        description: List income tax obligations for the party
  #        is: [genericErrors.internalServerError,
  #             genericErrors.notFound,
  #             genericErrors.clientOrAgentNotAuthorised,
  #             genericErrors.formatPartyIdentifier,
  #             genericErrors.formatStartDate,
  #             genericErrors.formatEndDate,
  #             genericErrors.formatType,
  #             genericErrors.rangeEndDateBeforeStartDate,
  #             obligationErrors.ruleDateRangeInvalid,
  #             obligationErrors.ruleStartDateNotSupported,
  #             obligationErrors.rangeDateTooLong,
  #             genericErrors.missingStartDate,
  #             genericErrors.missingEndDate, |
  #             obligationQueryParameters.obligations-regime,
  #             genericQueryParameters.startEndDateRange,
  #             genericHeaders.standardHeaders]
  #        responses:
  #          200:
  #            body:
  #              application/json:
  #                example: !include examples/by-regime/income-tax.json