    /{nino}:
      uriParameters:
        nino: baseTypes.Nino
      /{taxYear}:
        uriParameters:
          taxYear: baseTypes.TaxYear
        get:
          displayName: Investment GET
          description: List of Investment Reliefs
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
              body:
                application/json:
                  example: !include examples/investment.json
        put:
          displayName: Investment PUT
          description: Create/update Investment Reliefs submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            200:
          body:
            application/json:
              example: !include examples/investment.json
        delete:
          displayName: Investment DELETE
          description: Delete Investment Reliefs submission
          is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
          responses:
            204:
