#%RAML 1.0
title: Disclosures
baseUri: https://api.service.hmrc.gov.uk/individuals
version: 2020-07-29 14:10
documentation:
  - title: Disclosures
    content: Non-financial information i.e. tax avoidance & voluntary class 2 NICs, pertinent to the calculation, to be stored against the person.
uses:
  errors: ../generic/traits/errors.raml
  genericQueryParameters: ../generic/traits/queryParameters.raml
  wipErrors: traits/errors.raml
  genericHeaders: ../generic/traits/headers.raml
  baseTypes: ../generic/types/common/base-types.raml
/disclosures:
  /{nino}:
    uriParameters:
      nino: baseTypes.Nino
    /{taxYear}:
      uriParameters:
        taxYear: baseTypes.TaxYear
      get:
        displayName: Disclosures GET
        description: List of Disclosures
        is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
        responses:
          200:
            body:
              application/json:
                type: !include schemas/disclosures-sch.json
                example: !include examples/disclosures.json
      put:
        displayName: Disclosures PUT
        description: Create/update Disclosures submission
        is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
        responses:
          200:
        body:
          application/json:
            type: !include schemas/disclosures-sch.json
            example: !include examples/disclosures.json
      delete:
        displayName: Disclosures DELETE
        description: Delete Disclosures submission
        is: [errors.notFound,errors.clientOrAgentNotAuthorised,errors.formatNino,errors.formatTaxYear]
        responses:
          204:
